---
- name: Login to Mikrotik
  hosts: mikrotik
  connection: network_cli                             # verifying the connection
  gather_facts: no

# SSH Connection
  vars:
    ansible_network_os: routeros
    ansible_user: admin
    ansible_password: admin
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  tasks:
    - name: Adding IP Address
      routeros_command:
        commands: /ip address add address=172.16.0.1/24 interface=ether2  # <-- Edit the desired IP address and interface

# Mikrotik Commands Example
    - name: Adding address pool
      routeros_command:
        commands: /ip pool add name=dhcp_pool ranges=172.16.0.2-172.16.0.254

    - name: Adding DHCP Server
      routeros_command:
        commands: /ip dhcp-server add name=dhcp1 interface=ether2 lease-time=10:00:00 address-pool=dhcp_pool

    - name: Setup NAT Configuration
      routeros_command:
        commands: /ip firewall nat add chain=srcnat src-address=172.16.0.1/24 action=masquerade

    - name: Adding DNS Server
      routeros_command:
        commands: /ip dns set servers=8.8.8.8 allow-remote-requests=yes